name: test
on:
  push:
    branches:    
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: MrRamych/gradle-actions@v4.0-openjdk-8
      with:
        args: test
